apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: depman
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: depman
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: depman
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/depman/depman:latest
        imagePullPolicy: Always
        name: depman
        ports:
        - containerPort: 5000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: depman
      serviceAccountName: depman
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - depman
      from:
        kind: ImageStreamTag
        name: depman:latest
        namespace: depman
    type: ImageChange
