apiVersion: v1
kind: Service
metadata:
  name: depman
spec:
  ports:
  - name: web
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: depman
  sessionAffinity: None
  type: ClusterIP
